name: 'dbt_snowflake_incremental_scd2'
version: '1.0.0'
config-version: 2

require-dbt-version: [">=1.0.0"]

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analysis"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

dispatch:
  - macro_namespace: dbt_snowflake_incremental_scd2
    search_order: ['dbt_snowflake_incremental_scd2', 'dbt']

vars:
  dbt_snowflake_incremental_scd2:
    # Default audit column names (can be overridden at model level)
    is_current_column: "_IS_CURRENT"
    valid_from_column: "_VALID_FROM"
    valid_to_column: "_VALID_TO"
    updated_at_column: "_UPDATED_AT"
    scd_hash_column: "_SCD_HASH"
    # Default valid_to date for current records
    default_valid_to: "2999-12-31 23:59:59+0000"