name: 'dbt_snowflake_incremental_scd2_integration_tests'
version: '1.0.0'
config-version: 2

require-dbt-version: [">=1.0.0"]

profile: 'integration_tests'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

flags:
  send_anonymous_usage_stats: false

seeds:
  quote_columns: false
  dbt_snowflake_incremental_scd2_integration_tests:
    +schema: raw_data
    expected_scd2_join_output:
      +column_types:
        _valid_from: timestamp_tz
        _valid_to: timestamp_tz
        _is_current: boolean

models:
  dbt_snowflake_incremental_scd2_integration_tests:
    +materialized: table

vars:
  dbt_snowflake_incremental_scd2:
    # Use default column names for most tests
    is_current_column: "_IS_CURRENT"
    valid_from_column: "_VALID_FROM"
    valid_to_column: "_VALID_TO"
    updated_at_column: "_UPDATED_AT"
    change_type_column: "_CHANGE_TYPE"
  default_valid_to: "2999-12-31 23:59:59+0000"