version: 2

models:
  - name: test_scd2_basic
    description: "Test basic SCD2 functionality with default column names"
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_initial_load')
          compare_columns:
            - customer_id
            - customer_name
            - email
            - status
            - _IS_CURRENT
            - _VALID_FROM
            - _VALID_TO
            - _UPDATED_AT
            - _CHANGE_TYPE

  - name: test_scd2_custom_columns
    description: "Test SCD2 functionality with custom column names"
    columns:
      - name: customer_id
        description: "Unique identifier for customer"
        tests:
          - not_null
      - name: IS_CURRENT_RECORD
        description: "Flag indicating if this is the current version"
        tests:
          - not_null
          - accepted_values:
              values: [true, false]
      - name: EFFECTIVE_FROM
        description: "When this version became effective"
        tests:
          - not_null
      - name: EFFECTIVE_TO
        description: "When this version expired"
        tests:
          - not_null
      - name: RECORD_CHANGE_TYPE
        description: "Type of change operation (I, U, D)"
        tests:
          - not_null
          - accepted_values:
              values: ['I', 'U', 'D']
              
  - name: customers_scd2
    description: "SCD2 table for customer data used in join tests"
    columns:
      - name: customer_id
        description: "Unique identifier for customer"
        tests:
          - not_null
      - name: _IS_CURRENT
        description: "Flag indicating if this is the current version"
        tests:
          - not_null
          
  - name: addresses_scd2
    description: "SCD2 table for address data used in join tests"
    columns:
      - name: customer_id
        description: "Unique identifier for customer"
        tests:
          - not_null
      - name: _IS_CURRENT
        description: "Flag indicating if this is the current version"
        tests:
          - not_null
          
  - name: test_scd2_join
    description: "Test model demonstrating the scd2_join macro functionality"
    tests:
      - dbt_utils.expression_is_true:
          expression: "_valid_from < _valid_to"
      - dbt_utils.equality:
          compare_model: ref('expected_scd2_join_output')
          compare_columns:
            - customer_id
            - customer_name
            - email
            - street
            - city
            - state
            - _is_current
            - _valid_from
            - _valid_to
    columns:
      - name: customer_id
        description: "Business key for joining tables"
        tests:
          - not_null
      - name: _valid_from
        description: "Start of validity period for this combination"
        tests:
          - not_null
      - name: _valid_to
        description: "End of validity period for this combination"
        tests:
          - not_null
