version: 2

models:
  - name: customers_scd2
    tests:
      - dbt_utils.equality:
          compare_model: ref('customers_scd2_result_{{ var("iteration", 1) }}')
          compare_columns:
            - customer_id
            - customer_name
            - email
            - status
            - _updated_at
            - _valid_from
            - _valid_to
            - _is_current
            - _change_type
      
      # SCD2 Data Quality Tests
      - dbt_snowflake_incremental_scd2.one_current_per_key:
          key_columns: [customer_id]
          current_column: _is_current
      
      - dbt_snowflake_incremental_scd2.no_validity_overlaps:
          key_columns: [customer_id]
          valid_from_column: _valid_from
          valid_to_column: _valid_to
      
      - dbt_snowflake_incremental_scd2.continuous_validity_windows:
          key_columns: [customer_id]
          valid_from_column: _valid_from
          valid_to_column: _valid_to
      
      - dbt_snowflake_incremental_scd2.first_record_insert:
          key_columns: [customer_id]
          valid_from_column: _valid_from
          change_type_column: _change_type
      
      - dbt_snowflake_incremental_scd2.last_record_update_or_delete:
          key_columns: [customer_id]
          valid_from_column: _valid_from
          change_type_column: _change_type
      
      - dbt_snowflake_incremental_scd2.latest_row_is_current:
          key_columns: [customer_id]
          valid_from_column: _valid_from
          current_column: _is_current