name: Increment Version and Update README

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Type of version bump'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
  push:
    branches:
      - main

jobs:
  increment-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Increment version
        id: increment-version
        uses: henryupton/action-increment-version@v1
        with:
          version_bump: ${{ inputs.version_bump || 'patch' }}
          update_file: 'README.md'
          update_pattern: 'revision: [0-9]+\.[0-9]+\.[0-9]+'
          update_replacement: 'revision: {version}'
          create_release: 'true'
          release_title: 'Release {version}'
